AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A Swagger UI for AWS API Gateway.
Parameters:
  SwaggerSpecURL:
    Type: String
    Default: https://petstore.swagger.io/v2/swagger.json
    Description: Enter a publicly accessible URL to the Swagger spec JSON/YAML.
Resources:
  SwaggerUiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: The Lambda function that serves the Swagger UI.
      CodeUri: s3://aws-sam-apps-harish-km/0e0ce849d73806be952e34251d1710fe
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          SWAGGER_SPEC_URL:
            Ref: SwaggerSpecURL
      Events:
        SwaggerUiApi:
          Type: Api
          Properties:
            Path: /api-docs
            Method: GET
        SwaggerUiApiProxy:
          Type: Api
          Properties:
            Path: /api-docs/{proxy+}
            Method: GET
Outputs:
  SwaggerUiUrl:
    Description: Swagger UI URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api-docs/
Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-api-gateway-swagger-ui
    Description: A Swagger UI for AWS API Gateway.
    Author: Harish KM
    SpdxLicenseId: MIT
    LicenseUrl: s3://aws-sam-apps-harish-km/f7605c1e1bf9dce66bbf2c1e6ff98af1
    ReadmeUrl: s3://aws-sam-apps-harish-km/a7b19fefc438bf560fe50a42a285fd2a
    Labels:
    - swagger-ui
    - aws-sam
    - aws-api-gateway
    - aws-lambda
    - node-js
    HomePageUrl: https://github.com/harishkm7/aws-api-gateway-swagger-ui
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/harishkm7/aws-api-gateway-swagger-ui
